/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinktreeRouteImport } from './routes/linktree'
import { Route as IndexRouteImport } from './routes/index'

const LinktreeRoute = LinktreeRouteImport.update({
  id: '/linktree',
  path: '/linktree',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/linktree': typeof LinktreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/linktree': typeof LinktreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/linktree': typeof LinktreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/linktree'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/linktree'
  id: '__root__' | '/' | '/linktree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinktreeRoute: typeof LinktreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/linktree': {
      id: '/linktree'
      path: '/linktree'
      fullPath: '/linktree'
      preLoaderRoute: typeof LinktreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinktreeRoute: LinktreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
